<nav class="navbar navbar-expand-lg bg-light px-3">  
    <h1 class="d-none">Boutique de films</h1>  
    <a class="navbar-brand" href="/res04-auth/">Boutique films</a>  
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">  
        <li class="nav-item">  
            <a class="nav-link" href="/res04-auth/">Accueil</a>  
        </li>  
        <li class="nav-item">  
            <a class="nav-link" href="/res04-auth/produits">Liste des produits</a>  
        </li>  
        <li class="nav-item dropdown">  
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">  
                Catégories  
            </a>  
            <ul class="dropdown-menu">  
                <li><a class="dropdown-item" href="/res04-auth/categories/action">Action</a></li>  
                <li><a class="dropdown-item" href="/res04-auth/categories/heroic-fantasy">Heroic-Fantasy</a></li>  
                <li><a class="dropdown-item" href="/res04-auth/categories/science-fiction">Science-Fiction</a></li>  
            </ul>  
        </li>
        <?php if(isset($_SESSION["user_id"])) : ?>
            <li class="nav-item">  
                <a class="nav-link" href="/res04-auth/logout">Déconnexion</a>  
            </li>
        <?php else : ?>
            <li class="nav-item">  
                <a class="nav-link" href="/res04-auth/creer-un-compte">Inscription</a>  
            </li>  
            <li class="nav-item">  
                <a class="nav-link" href="/res04-auth/connexion">Connexion</a>  
            </li>
        <?php endif; ?>
    </ul>  
</nav>
